spring:
  application:
    name: JobFinder
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: offers
      username: root
      password: example
      authentication-database: admin
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

scheduler:
  enabled: true

offer:
  fetcher:
    rest:
      template:
        config:
          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com:5057
          port: 5057
          connectionTimeout: 4000
          readTimeout: 4000
    scheduler:
        fixedDelay: PT3H  # 10800000 = 3 hours in milliseconds

