spring:
  application:
    name: JobFinder
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: mongodb://admin:admin@localhost:27017/jobfinderdb

offer:
  fetcher:
    rest:
      template:
        config:
          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com:5057/offers
          port: 5057
          connectionTimeout: 4000
          readTimeout: 4000

