offer:
  fetcher:
    scheduler:
        fixedDelay: PT1S  # every second for integration tests
scheduler:
  enabled: false # disable scheduling for integration tests EXCEPT for scheduler integration tests

spring:
  cache:
    type: none
    redis:
        time-to-live: PT10S